services:
  api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=*
    volumes:
      - ./packages/api/src:/app/packages/api/src
      - ./packages/shared:/app/packages/shared
    ports:
      - "9229:9229"
  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./packages/ui/src:/app/packages/ui/src
      - ./packages/ui/public:/app/packages/ui/public
      - ./packages/ui/index.html:/app/packages/ui/index.html
      - ./packages/ui/vite.config.ts:/app/packages/ui/vite.config.ts
      - ./packages/ui/tailwind.config.js:/app/packages/ui/tailwind.config.js
      - ./packages/ui/postcss.config.js:/app/packages/ui/postcss.config.js
      - ./packages/shared:/app/packages/shared
    ports:
      - "5173:5173"
